"""baseline: adopt existing schema

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-16

The 19 tables already exist in production, created by Drizzle and by
`script/migrate.ts`. Production therefore adopts this revision with

    alembic stamp head

which records it as applied WITHOUT running it. `upgrade()` only ever executes against a
fresh database — a local dev DB, CI, or the staging instance used by the contract-diff
harness.

It builds from `SQLModel.metadata` rather than 19 hand-written `op.create_table()` calls
on purpose: transcribing ~200 columns by hand is exactly how a baseline drifts from the
models it is supposed to describe. Deriving it makes the two identical by construction.
Subsequent revisions are ordinary autogenerated ops.
"""

from collections.abc import Sequence

from sqlmodel import SQLModel

import app.models  # noqa: F401  (registers all 19 tables on the metadata)
from alembic import op

revision: str = "0001_baseline"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # checkfirst=True keeps this safe on a partially-provisioned database.
    SQLModel.metadata.create_all(bind=op.get_bind(), checkfirst=True)


def downgrade() -> None:
    SQLModel.metadata.drop_all(bind=op.get_bind(), checkfirst=True)
