#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Production DATABASE_URL only. Never write it into .env.local (that file is
# local supabase start on :54322).
_REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$_REPO_ROOT"
ENV_FILE="$_REPO_ROOT/.env.schema.apply"

_db_fingerprint() {
  python3 -c '
from urllib.parse import urlparse, unquote
import sys
u = urlparse(sys.argv[1])
if not u.hostname:
    print("unparseable")
    raise SystemExit(0)
user = unquote(u.username or "")
print(f"host={u.hostname} port={u.port or 5432} user={user}")
' "$1"
}

TOTAL_STAGES=5

banner "Apply SnapSync schema on empty Supabase"

# ── 1. Guardrails ─────────────────────────────────────────────────────────
stage "Guardrails"
say "This creates the SnapSync tables on an empty Supabase Postgres."
say "Grouping and New listing persist on public.images. Without that table they fail."
warn "Do not paste the DATABASE_URL from .env.local (127.0.0.1:54322)."
warn "Do not run this against a database that already has seller data unless you mean to."
step "You will copy the Session pooler URI (port 5432) from the empty project."
step "You will confirm Railway DATABASE_URL is that same project."
step "Then this script runs: cd api-py && uv run alembic upgrade head"
if ! confirm "This empty Supabase is the database Railway uses, and it has no tables?"; then
  say "Stopped. If Railway still points at a different project, fix DATABASE_URL there first."
  exit 0
fi

# ── 2. Copy session-pooler URI ────────────────────────────────────────────
stage "Supabase DATABASE_URL"
open_url "https://supabase.com/dashboard"
step "Open the empty project (Table Editor → public should list no SnapSync tables)."
step "Click Connect (top right), or Project Settings → Database."
step "Connection string → URI."
step "Method: Session pooler. Port must be 5432."
note "Not Transaction pooler (6543). Not Direct if it is IPv6-only from this laptop."
note "The username often looks like postgres.<project-ref> on pooler.supabase.com."
ask_secret DATABASE_URL "Paste the Session pooler DATABASE_URL:"
if [[ -z "$DATABASE_URL" ]]; then
  warn "DATABASE_URL is empty. Cannot migrate."
  exit 1
fi
if [[ "$DATABASE_URL" == *"localhost"* || "$DATABASE_URL" == *"127.0.0.1"* ]]; then
  warn "That string looks local. Railway and this wizard need the Supabase URI."
  if ! confirm "Use it anyway?"; then
    ask_secret DATABASE_URL "Paste the Session pooler DATABASE_URL:"
  fi
fi
if [[ "$DATABASE_URL" == *":6543/"* || "$DATABASE_URL" == *":6543" ]]; then
  warn "Port 6543 is Transaction pooler. DDL is more reliable on Session pooler :5432."
  if confirm "Go back and copy the Session pooler URI instead?"; then
    open_url "https://supabase.com/dashboard"
    ask_secret DATABASE_URL "Paste the Session pooler DATABASE_URL (port 5432):"
  fi
fi
note "Fingerprint (no password): $(_db_fingerprint "$DATABASE_URL")"
write_env DATABASE_URL "$DATABASE_URL"

# ── 3. Railway is the same project ────────────────────────────────────────
stage "Railway DATABASE_URL matches"
open_url "https://railway.app/dashboard"
step "Open the project that serves api.snapsyncai.co.uk / snapsyncai-production."
step "Click the FastAPI API service (not Redis, not a frontend)."
step "Variables → DATABASE_URL → Reveal."
step "Host and user must match the fingerprint above. Password stays hidden."
note "health/db can be green even when public.images does not exist (it only runs SELECT 1)."
ask_secret RAILWAY_DATABASE_URL "Paste Railway DATABASE_URL to compare (or Enter to skip):"
if [[ -n "${RAILWAY_DATABASE_URL:-}" ]]; then
  note "Railway fingerprint: $(_db_fingerprint "$RAILWAY_DATABASE_URL")"
  _SUPA_FP=$(_db_fingerprint "$DATABASE_URL")
  _RAIL_FP=$(_db_fingerprint "$RAILWAY_DATABASE_URL")
  if [[ "$_SUPA_FP" != "$_RAIL_FP" ]]; then
    warn "Fingerprints differ. Applying schema here will not fix production grouping."
    warn "Update Railway Variables to this Session pooler URI, then re-run."
    if ! confirm "Apply schema to the pasted Supabase URI anyway?"; then
      say "Stopped. Align Railway DATABASE_URL with this project, then re-run."
      exit 0
    fi
  else
    note "Host/user/port match. Same database."
  fi
else
  if ! confirm "Railway DATABASE_URL is this same project (host and user match)?"; then
    say "Stopped. Paste both URIs on a re-run so they can be compared."
    exit 0
  fi
fi

# ── 4. Apply Alembic ──────────────────────────────────────────────────────
stage "Run alembic upgrade head"
say "This creates public.images and the other core-loop tables on that database."
note "Revision 0001 uses create_all on a fresh database; later revisions are IF NOT EXISTS / IF EXISTS."
if ! confirm "Run migrations now against the fingerprinted database?"; then
  say "Stopped before any DDL. Re-run when ready."
  exit 0
fi
if ! command -v uv >/dev/null 2>&1; then
  warn "uv is not on PATH. Install it, then re-run this wizard."
  exit 1
fi
say "Running alembic (DATABASE_URL is in the environment, not printed)…"
if ! (
  cd "$_REPO_ROOT/api-py"
  DATABASE_URL="$DATABASE_URL" uv run alembic upgrade head
); then
  warn "alembic upgrade head failed. The database was not fully migrated."
  SKIPPED+=("alembic upgrade head — fix the error above and re-run")
  pause "Press Enter to finish with a failure summary."
  finish
  exit 1
fi
note "alembic upgrade head finished."

# ── 5. Verify public.images ───────────────────────────────────────────────
stage "Verify public.images"
say "Checking Postgres for the tables grouping and New listing need."
_PROBE_PY=$(cat <<'PY'
import asyncio
from sqlalchemy import text
from app.db import create_engine
NEEDED = ("images", "shopify_connections", "paid_sessions", "subscriptions", "user_credits", "allowance_spends")
async def main():
    engine = create_engine()
    async with engine.connect() as conn:
        rows = await conn.execute(text(
            "SELECT tablename FROM pg_tables "
            "WHERE schemaname = 'public' AND tablename IN "
            "('images','shopify_connections','paid_sessions',"
            "'subscriptions','user_credits','allowance_spends') "
            "ORDER BY 1"
        ))
        have = {r[0] for r in rows}
    await engine.dispose()
    print("have:" + (",".join(sorted(have)) if have else ""))
    print("missing:" + (",".join(n for n in NEEDED if n not in have)))
    print("images_ok:" + ("yes" if "images" in have else "no"))
asyncio.run(main())
PY
)
_PROBE_FILE=$(mktemp)
printf '%s\n' "$_PROBE_PY" > "$_PROBE_FILE"
_PROBE_OUT=$(
  cd "$_REPO_ROOT/api-py"
  DATABASE_URL="$DATABASE_URL" uv run python "$_PROBE_FILE"
) || true
rm -f "$_PROBE_FILE"
note "$_PROBE_OUT"
if [[ "$_PROBE_OUT" != *"images_ok:yes"* ]]; then
  warn "public.images is still missing. Grouping will keep failing."
  SKIPPED+=("public.images still missing after alembic — inspect the probe output")
else
  note "public.images exists. Grouping can persist product_group_id."
fi
open_url "https://supabase.com/dashboard"
step "Reload Table Editor → public. You should see images and the other core tables."
step "Then in production: New listing — upload photos, group them, create the Product."
note "API health/db staying green was never the table check. This probe is."
pause "Press Enter after you have reloaded Table Editor."

# ──────────────────────────────────────────────────────────────────────────

finish
