#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Persist the Railway *reference* only. Never write a redis:// password here,
# and never write production Redis into .env.local.
_REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$_REPO_ROOT"
ENV_FILE="$_REPO_ROOT/.env.railway.prod"

TOTAL_STAGES=5

banner "Railway Redis Open Source (catalogue cache)"

# ── 1. Guardrails ─────────────────────────────────────────────────────────
stage "Guardrails"
say "This adds Railway's built-in Redis (Open Source, redis Docker image) and"
say "points the FastAPI service at it. That is the one source of REDIS_URL."
warn "Do not paste a redis:// password. Use a reference: \${{Redis.REDIS_URL}}"
warn "Do not enable Public Access / TCP Proxy — FastAPI is in the same project."
warn "Do not write REDIS_URL into .env.local (local compose Redis stays local)."
warn "Do not add Railway Postgres. Production data stays on Supabase."
note "Docs: https://docs.railway.com/databases/redis"
note "Cache is optional: missing Redis still serves GET /api/images from Postgres."
if ! confirm "Continue?"; then
  say "Stopped. Re-run when you are on the production Railway project."
  exit 0
fi

# ── 2. Add Redis Open Source ──────────────────────────────────────────────
stage "Add Redis Open Source"
open_url "https://railway.app/dashboard"
step "Open the project that serves snapsyncai-production.up.railway.app"
step "(that is also api.snapsyncai.co.uk)."
say ""
say "If a Redis card is already on the canvas, skip the add — do not create a second one."
say "If not:"
step "Click + New on the Project Canvas."
step "Choose Database, then Redis."
step "Or press Cmd/Ctrl+K, type Redis, and pick the built-in Redis database."
note "Pick Railway Redis / Redis Open Source (the redis Docker image)."
note "Do not pick Redis Cloud, a marketplace template, KeyDB, or Valkey."
note "Leave the service name as Redis if Railway offers a rename."
step "Wait until the Redis card shows Running (first deploy is automatic)."
if ! confirm "Is Redis Open Source on the canvas and Running?"; then
  say "Stopped. Finish the add, wait for Running, then re-run this wizard."
  exit 0
fi

# ── 3. Wire REDIS_URL on FastAPI ──────────────────────────────────────────
stage "Wire REDIS_URL on FastAPI"
say "The API must reference the Redis service. Do not copy the connection string."
step "Read the Redis card title on the canvas — usually Redis."
ask REDIS_SERVICE_NAME "Redis canvas name (Enter = Redis):"
[[ -z "$REDIS_SERVICE_NAME" ]] && REDIS_SERVICE_NAME="Redis"
REDIS_URL="\${{${REDIS_SERVICE_NAME}.REDIS_URL}}"
note "You will set REDIS_URL=$REDIS_URL on FastAPI."
step "Click the FastAPI API service (not Redis, not a Function, not the frontend)."
step "Open the Variables tab."
step "Click New Variable."
step "Name: REDIS_URL"
step "Value: type $ then pick ${REDIS_SERVICE_NAME} → REDIS_URL from autocomplete."
step "If autocomplete misses: paste $REDIS_URL exactly (case-sensitive name)."
note "Railway docs: service Variables → New Variable; template is \${{SERVICE_NAME.VAR}}."
if ! confirm "REDIS_URL is saved as a reference on the FastAPI service?"; then
  say "Stopped. Add the reference, then re-run — this stage is safe to repeat."
  exit 0
fi
write_env REDIS_URL "$REDIS_URL"

# ── 4. Deploy ─────────────────────────────────────────────────────────────
stage "Deploy FastAPI"
say "Changing a variable stages a deploy. It does not go live until you confirm."
step "Still on the FastAPI service: review the staged variable change."
step "Click Deploy."
step "Wait until the new deployment is Success."
note "You do not need to redeploy Redis. You do not need to touch Vercel."
if ! confirm "Did FastAPI finish a successful deploy after REDIS_URL landed?"; then
  say "Stopped. Click Deploy, wait for Success, then re-run from here if needed."
  exit 0
fi

# ── 5. Verify ─────────────────────────────────────────────────────────────
stage "Verify API still boots"
say "There is no Redis health route. Success = FastAPI still healthy with REDIS_URL set."
_RAILWAY_HOST="https://snapsyncai-production.up.railway.app"
_API_HOST="https://api.snapsyncai.co.uk"
step "GET $_RAILWAY_HOST/api/health     — want {\"status\":\"ok\",\"service\":\"snapsyncai-api\"}"
step "GET $_RAILWAY_HOST/api/health/db  — want databaseOk (Postgres / Supabase, not Redis)"
step "GET $_API_HOST/api/health         — same, if DNS already points here"
if command -v curl >/dev/null 2>&1; then
  note "railway host /api/health:"
  curl -sS --max-time 20 "$_RAILWAY_HOST/api/health" || true
  printf '\n'
  note "railway host /api/health/db:"
  curl -sS --max-time 20 "$_RAILWAY_HOST/api/health/db" || true
  printf '\n'
  note "api. host /api/health:"
  curl -sS --max-time 20 "$_API_HOST/api/health" || true
  printf '\n'
else
  warn "curl missing — open those URLs yourself."
fi
warn "If FastAPI crash-loops, REDIS_URL is a pasted string or the service name is wrong."
warn "Fix: Variables → REDIS_URL = \${{Redis.REDIS_URL}} matching the canvas name."
note "Catalogue cache is now on for GET /api/images. A down Redis still fails open to Postgres."
pause "Press Enter to finish."

# ──────────────────────────────────────────────────────────────────────────

finish
