#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Persist Railway production values only. Never write these into .env.local.
_REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$_REPO_ROOT"
ENV_FILE="$_REPO_ROOT/.env.railway.prod"

TOTAL_STAGES=9

banner "Railway API env (vendors → FastAPI)"

# ── 1. Guardrails ─────────────────────────────────────────────────────────
stage "Guardrails"
say "This copies production SERVER env onto the FastAPI service already on Railway."
say "It does not deploy the seller UI. It does not change DNS. Vercel only hosts www — not the database."
warn "Do not paste values from .env.local (localhost DB, local Supabase, empty Clerk)."
warn "Do not set DEV_BYPASS_AUTH or any VITE_* key on Railway."
step "Source of truth: each vendor dashboard (Supabase, Clerk, Stripe, OpenAI, Shopify)."
step "Do not copy DATABASE_URL from Vercel — that is a leftover Express copy and may be wrong."
if ! confirm "Continue with production values only?"; then
  say "Stopped. Re-run when you have vendor live keys."
  exit 0
fi

# ── 2. Database ───────────────────────────────────────────────────────────
stage "Database"
open_url "https://supabase.com/dashboard"
step "Open the existing production SnapSync project (the one that already has seller data)."
step "Project Settings → Database → Connection string → URI."
step "Method: Session pooler. Port must be 5432, not Transaction 6543."
note "This is a postgresql:// URI. The Project URL (https://….supabase.co) is SUPABASE_URL, not DATABASE_URL."
note "Do not copy DATABASE_URL from Vercel."
ask_secret DATABASE_URL "Paste production DATABASE_URL (Session pooler :5432):"
if [[ -z "$DATABASE_URL" ]]; then
  warn "DATABASE_URL is empty — FastAPI will crash on boot (Pydantic: database_url required)."
  ask_secret DATABASE_URL "Paste production DATABASE_URL:"
fi
if [[ "$DATABASE_URL" == http://* || "$DATABASE_URL" == https://* ]]; then
  warn "That is the Project URL, not Postgres. FastAPI will still crash."
  ask_secret DATABASE_URL "Paste the postgresql:// Session pooler URI:"
fi
if [[ "$DATABASE_URL" == *"localhost"* || "$DATABASE_URL" == *"127.0.0.1"* ]]; then
  warn "That string looks local. Railway cannot reach supabase start on your laptop."
  ask_secret DATABASE_URL "Paste the production Session pooler DATABASE_URL:"
fi
if [[ "$DATABASE_URL" == *":6543/"* || "$DATABASE_URL" == *":6543" ]]; then
  warn "Port 6543 is Transaction pooler. Prefer Session pooler on 5432."
  open_url "https://supabase.com/dashboard"
  ask_secret DATABASE_URL "Paste the Session pooler DATABASE_URL (port 5432):"
fi
write_env DATABASE_URL "$DATABASE_URL"

# ── 3. Clerk ──────────────────────────────────────────────────────────────
stage "Clerk"
open_url "https://dashboard.clerk.com"
step "Open the live instance (not development)."
step "Configure → API keys. Copy Publishable and Secret."
ask CLERK_PUBLISHABLE_KEY "Paste CLERK_PUBLISHABLE_KEY (pk_live_…):"
ask_secret CLERK_SECRET_KEY "Paste CLERK_SECRET_KEY (sk_live_…):"
write_env CLERK_PUBLISHABLE_KEY "$CLERK_PUBLISHABLE_KEY"
write_env CLERK_SECRET_KEY "$CLERK_SECRET_KEY"

# ── 4. Stripe ─────────────────────────────────────────────────────────────
stage "Stripe"
note "Stripe Dashboard must be in live mode (toggle Test mode OFF)."
open_url "https://dashboard.stripe.com/apikeys"
step "API keys: Publishable (pk_live_) and Secret (sk_live_ Reveal)."
open_url "https://dashboard.stripe.com/webhooks"
step "Webhooks: open the existing live endpoint → Signing secret → Reveal."
ask STRIPE_PUBLISHABLE_KEY "Paste STRIPE_PUBLISHABLE_KEY (pk_live_…):"
ask_secret STRIPE_SECRET_KEY "Paste STRIPE_SECRET_KEY:"
ask_secret STRIPE_WEBHOOK_SECRET "Paste STRIPE_WEBHOOK_SECRET (whsec_…):"
write_env STRIPE_PUBLISHABLE_KEY "$STRIPE_PUBLISHABLE_KEY"
write_env STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"
write_env STRIPE_WEBHOOK_SECRET "$STRIPE_WEBHOOK_SECRET"

# ── 5. Supabase + OpenAI ──────────────────────────────────────────────────
stage "Supabase and OpenAI"
open_url "https://supabase.com/dashboard"
step "Same production project as DATABASE_URL. Settings → API."
step "Copy Project URL (https://….supabase.co) — that is SUPABASE_URL, not DATABASE_URL."
step "Copy anon public → SUPABASE_ANON_KEY."
step "Reveal service_role (secret) → SUPABASE_SERVICE_ROLE_KEY. Photos fail without this."
open_url "https://platform.openai.com/api-keys"
step "Copy the live OpenAI key Express already used."
ask SUPABASE_URL "Paste SUPABASE_URL (https://….supabase.co):"
ask_secret SUPABASE_ANON_KEY "Paste SUPABASE_ANON_KEY:"
ask_secret SUPABASE_SERVICE_ROLE_KEY "Paste SUPABASE_SERVICE_ROLE_KEY:"
ask_secret AI_INTEGRATIONS_OPENAI_API_KEY "Paste AI_INTEGRATIONS_OPENAI_API_KEY:"
write_env SUPABASE_URL "$SUPABASE_URL"
write_env SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"
write_env AI_INTEGRATIONS_OPENAI_API_KEY "$AI_INTEGRATIONS_OPENAI_API_KEY"

# ── 6. Shopify ────────────────────────────────────────────────────────────
stage "Shopify"
open_url "https://partners.shopify.com"
step "Open the SnapSync app → Client credentials. Copy API key and secret."
note "CONNECTION_ENCRYPTION_KEY has no vendor page. If you do not already have it, it is the existing production secret (old Express / Railway), not a new value."
ask_secret SHOPIFY_API_KEY "Paste SHOPIFY_API_KEY:"
ask_secret SHOPIFY_API_SECRET "Paste SHOPIFY_API_SECRET:"
ask_secret CONNECTION_ENCRYPTION_KEY "Paste CONNECTION_ENCRYPTION_KEY:"
write_env SHOPIFY_API_KEY "$SHOPIFY_API_KEY"
write_env SHOPIFY_API_SECRET "$SHOPIFY_API_SECRET"
write_env CONNECTION_ENCRYPTION_KEY "$CONNECTION_ENCRYPTION_KEY"

# ── 7. Railway-only (not copied from local) ───────────────────────────────
stage "Railway-only values"
say "These are not Vercel function vars. Write them exactly as shown."
warn "Skip DEV_BYPASS_AUTH. Skip VITE_API_ORIGIN — that stays on Vercel later."
ENVIRONMENT="production"
APP_BASE_URL="https://www.snapsyncai.co.uk"
CORS_ALLOW_ORIGINS="https://www.snapsyncai.co.uk,https://snapsyncai.co.uk"
write_env ENVIRONMENT "$ENVIRONMENT"
write_env APP_BASE_URL "$APP_BASE_URL"
write_env CORS_ALLOW_ORIGINS "$CORS_ALLOW_ORIGINS"
note "File ready: $ENV_FILE"

# ── 8. Paste into Railway and deploy ──────────────────────────────────────
stage "Paste into Railway"
open_url "https://railway.app/dashboard"
step "Open the project that serves snapsyncai-production.up.railway.app."
step "Click the FastAPI API service (not a Function, not a frontend)."
step "Open the Variables tab."
step "Open RAW Editor. Paste the full contents of .env.railway.prod (not .env.local)."
step "Save. Review the staged change. Click Deploy."
note "Railway docs: service → Variables → New Variable, or RAW Editor for a .env block."
if confirm "Open .env.railway.prod in an editor so you can copy it?"; then
  if command -v open >/dev/null 2>&1; then
    open "$ENV_FILE" || warn "Could not open the file — copy it from $ENV_FILE"
  else
    note "Copy from $ENV_FILE"
  fi
fi
pause "Press Enter after Railway has started the new deploy."

# ── 9. Verify ─────────────────────────────────────────────────────────────
stage "Verify Railway health"
say "Checking the Railway host only. DNS for api.snapsyncai.co.uk is unchanged."
_HOST="https://snapsyncai-production.up.railway.app"
step "GET $_HOST/api/health  — want {\"status\":\"ok\",\"service\":\"snapsyncai-api\"}"
step "GET $_HOST/api/health/db — want databaseOk true"
if command -v curl >/dev/null 2>&1; then
  note "health:"
  curl -sS --max-time 20 "$_HOST/api/health" || true
  printf '\n'
  note "health/db:"
  curl -sS --max-time 20 "$_HOST/api/health/db" || true
  printf '\n'
  note "clerk-config:"
  curl -sS --max-time 20 "$_HOST/api/auth/clerk-config" || true
  printf '\n'
  note "payments/config:"
  curl -sS --max-time 20 "$_HOST/api/payments/config" || true
  printf '\n'
else
  warn "curl missing — run those URLs yourself."
fi
warn "If health/db is still 500, DATABASE_URL is wrong or unreachable. Do not point api. DNS at Railway."
warn "Do not set VITE_API_ORIGIN on Vercel until health/db is 200."
pause "Press Enter to finish."

# ──────────────────────────────────────────────────────────────────────────

finish
