#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Personal production test Plan for lefterisgilmaz@gmail.com.
# Coupon lives in Stripe. Secret key + webhook secret are persisted locally.
_REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$_REPO_ROOT"
ENV_FILE="$_REPO_ROOT/.env.railway.prod"

TOTAL_STAGES=7

banner "Production test Plan (coupon + webhook)"

# ── 1. Guardrails ─────────────────────────────────────────────────────────
stage "Guardrails"
say "This is a live Stripe Plan for one seller, not an email backdoor in code."
say "lefterisgilmaz@gmail.com stays free until Stripe says Plan, then Settings → Subscribe."
warn "Use the LIVE Stripe dashboard (Test mode OFF)."
warn "Do not create a customer-facing promotion code. Anyone with that code would get 100% off."
warn "Do not set DEV_BYPASS_AUTH on Railway."
warn "Cancel in Settings when you are done testing — this coupon is forever until you do."
if ! confirm "Continue with live Stripe for this one email?"; then
  say "Stopped. Re-run when you are on the live Stripe account."
  exit 0
fi

# ── 2. Live secret key ────────────────────────────────────────────────────
stage "Live secret key"
say "Subscribe failed because STRIPE_SECRET_KEY is an mk_ key ID, not the secret."
open_url "https://dashboard.stripe.com/apikeys"
step "Confirm Test mode is OFF (live)."
step "Secret key row → Reveal live key → copy."
step "The value must start with sk_live_ (or rk_live_ for a restricted key)."
warn "Do not copy the key ID (mk_…). That is the row id, not the secret."
warn "Do not copy pk_live_ here — that is STRIPE_PUBLISHABLE_KEY."
ask_secret STRIPE_SECRET_KEY "Paste STRIPE_SECRET_KEY (sk_live_…):"
if [[ "$STRIPE_SECRET_KEY" == mk_* ]]; then
  warn "That is a key ID. Reveal the secret again."
  ask_secret STRIPE_SECRET_KEY "Paste sk_live_…:"
fi
if [[ "$STRIPE_SECRET_KEY" != sk_live_* && "$STRIPE_SECRET_KEY" != rk_live_* ]]; then
  warn "Live secret keys start with sk_live_ or rk_live_."
  ask_secret STRIPE_SECRET_KEY "Paste STRIPE_SECRET_KEY:"
fi
write_env STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"
open_url "https://railway.app/dashboard"
step "FastAPI service (api.snapsyncai.co.uk) → Variables → STRIPE_SECRET_KEY."
step "Replace with the sk_live_… value. Save. Deploy. Wait for Success."
if ! confirm "STRIPE_SECRET_KEY on FastAPI is sk_live_… and deploy succeeded?"; then
  say "Stopped. Set the variable, wait for Success, then re-run."
  exit 0
fi

# ── 3. Webhook signing secret ─────────────────────────────────────────────
stage "Webhook signing secret"
say "Railway currently has a URL in STRIPE_WEBHOOK_SECRET. It must be whsec_…"
open_url "https://dashboard.stripe.com/webhooks"
step "Confirm Test mode is OFF (live)."
step "Open the endpoint whose URL is https://api.snapsyncai.co.uk/api/stripe/webhook"
step "If it does not exist: Add endpoint → that URL → events checkout.session.completed,"
step "customer.subscription.updated, customer.subscription.deleted → Add."
step "On that endpoint: Signing secret → Reveal → copy. It starts with whsec_"
note "That string is the secret. The URL is not."
ask_secret STRIPE_WEBHOOK_SECRET "Paste STRIPE_WEBHOOK_SECRET (whsec_…):"
if [[ "$STRIPE_WEBHOOK_SECRET" != whsec_* ]]; then
  warn "That does not start with whsec_. FastAPI will reject Stripe signatures."
  open_url "https://dashboard.stripe.com/webhooks"
  ask_secret STRIPE_WEBHOOK_SECRET "Paste the Reveal signing secret (whsec_…):"
fi
if [[ "$STRIPE_WEBHOOK_SECRET" == http://* || "$STRIPE_WEBHOOK_SECRET" == https://* ]]; then
  warn "That is the endpoint URL, not the signing secret."
  ask_secret STRIPE_WEBHOOK_SECRET "Paste whsec_… from Reveal:"
fi
write_env STRIPE_WEBHOOK_SECRET "$STRIPE_WEBHOOK_SECRET"
open_url "https://railway.app/dashboard"
step "Open the FastAPI service that serves api.snapsyncai.co.uk (snapsyncai)."
step "Variables → find STRIPE_WEBHOOK_SECRET."
step "Replace the value with the same whsec_… you just pasted. Save. Deploy."
if ! confirm "STRIPE_WEBHOOK_SECRET on FastAPI is whsec_… and a new deploy started?"; then
  say "Stopped. Set the variable, deploy, then re-run — this stage is safe to repeat."
  exit 0
fi

# ── 3. Create coupon ──────────────────────────────────────────────────────
stage "Create 100% forever coupon"
open_url "https://dashboard.stripe.com/coupons"
step "Confirm Test mode is OFF."
step "Create coupon (or New)."
step "Percent off: 100."
step "Duration: Forever."
step "Do not enable a customer-facing promotion code."
step "Leave max redemptions empty (you will apply it to one customer next)."
step "Save."
if ! confirm "A 100% forever coupon exists (no promo code)?"; then
  say "Stopped. Finish the coupon, then re-run."
  exit 0
fi

# ── 4. Customer + apply coupon ────────────────────────────────────────────
stage "Apply coupon to the customer"
open_url "https://dashboard.stripe.com/customers"
step "Search lefterisgilmaz@gmail.com."
step "If missing: New customer → email lefterisgilmaz@gmail.com → save."
step "Open that customer → Actions → Apply coupon → pick the 100% forever coupon → Submit."
note "The discount must show on the customer page before you subscribe."
if ! confirm "That customer shows the 100% forever coupon?"; then
  say "Stopped. Apply the coupon, then re-run."
  exit 0
fi

# ── 5. Subscribe in the app ───────────────────────────────────────────────
stage "Settings → Subscribe"
say "Checkout still asks for a card. You should be charged £0."
open_url "https://www.snapsyncai.co.uk"
step "Sign in as lefterisgilmaz@gmail.com (Clerk live)."
step "Open Settings → Subscribe → monthly (£19/mo)."
step "On Stripe Checkout: if the total is not £0, STOP and come back — coupon did not attach."
step "If total is £0: enter a card, complete checkout, wait for redirect to www."
warn "If Checkout still shows £19, do not pay. The customer coupon did not apply."
if ! confirm "Checkout completed at £0 and you landed back on www?"; then
  say "Stopped. If you were charged £19, cancel in Settings and tell the agent."
  exit 0
fi

# ── 6. Confirm generate works ─────────────────────────────────────────────
stage "Confirm the Plan landed"
say "Verify unlocks Generate All. Then confirm product facts on a product."
step "Settings should show a Plan (not Subscribe)."
step "Open a product → Confirm textile composition if that button is still there."
step "Generate All should be enabled (not the NEED_PLAN sentence)."
if command -v curl >/dev/null 2>&1; then
  note "api health (Plan is not a health field):"
  curl -sS --max-time 20 "https://api.snapsyncai.co.uk/api/health" || true
  printf '\n'
fi
warn "Search demand is still unconfigured. That only blocks Refresh, not Generate All."
warn "Cancel in Settings when you are done so this forever coupon stops meaning a live Plan."
pause "Press Enter to finish."

# ──────────────────────────────────────────────────────────────────────────

finish
